CPUEAXH_ERR_OK = 0
CPUEAXH_ERR_NOMEM = 1
CPUEAXH_ERR_ARG = 2
CPUEAXH_ERR_ARCH = 3
CPUEAXH_ERR_MODE = 4
CPUEAXH_ERR_MAP = 5
CPUEAXH_ERR_READ_UNMAPPED = 6
CPUEAXH_ERR_WRITE_UNMAPPED = 7
CPUEAXH_ERR_FETCH_UNMAPPED = 8
CPUEAXH_ERR_EXCEPTION = 9
CPUEAXH_ERR_HOOK = 10
CPUEAXH_ERR_READ_PROT = 11
CPUEAXH_ERR_WRITE_PROT = 12
CPUEAXH_ERR_FETCH_PROT = 13
CPUEAXH_ERR_PATCH = 14

CPUEAXH_ARCH_X86 = 1
CPUEAXH_MODE_64 = 8

CPUEAXH_MEMORY_MODE_GUEST = 0
CPUEAXH_MEMORY_MODE_HOST = 1

CPUEAXH_PROT_READ = 1
CPUEAXH_PROT_WRITE = 2
CPUEAXH_PROT_EXEC = 4

CPUEAXH_MEM_ATTR_USER = 1

CPUEAXH_HOOK_CODE_PRE = 1
CPUEAXH_HOOK_CODE_POST = 2
CPUEAXH_HOOK_MEM_READ = 3
CPUEAXH_HOOK_MEM_WRITE = 4
CPUEAXH_HOOK_MEM_FETCH = 5
CPUEAXH_HOOK_MEM_READ_UNMAPPED = 6
CPUEAXH_HOOK_MEM_WRITE_UNMAPPED = 7
CPUEAXH_HOOK_MEM_FETCH_UNMAPPED = 8
CPUEAXH_HOOK_MEM_READ_PROT = 9
CPUEAXH_HOOK_MEM_WRITE_PROT = 10
CPUEAXH_HOOK_MEM_FETCH_PROT = 11

CPUEAXH_ESCAPE_INSN_NONE = 0
CPUEAXH_ESCAPE_INSN_SYSCALL = 1
CPUEAXH_ESCAPE_INSN_SYSENTER = 2
CPUEAXH_ESCAPE_INSN_INT = 3
CPUEAXH_ESCAPE_INSN_INT3 = 4
CPUEAXH_ESCAPE_INSN_CPUID = 5
CPUEAXH_ESCAPE_INSN_XGETBV = 6
CPUEAXH_ESCAPE_INSN_RDTSC = 7
CPUEAXH_ESCAPE_INSN_RDTSCP = 8
CPUEAXH_ESCAPE_INSN_RDRAND = 9
CPUEAXH_ESCAPE_INSN_HLT = 10
CPUEAXH_ESCAPE_INSN_IN = 11
CPUEAXH_ESCAPE_INSN_OUT = 12
CPUEAXH_ESCAPE_INSN_WRITECRX = 13
CPUEAXH_ESCAPE_INSN_READCRX = 14
CPUEAXH_ESCAPE_INSN_RDSSPD = 15
CPUEAXH_ESCAPE_INSN_RDSSPQ = 16

CPUEAXH_EXCEPTION_NONE = 0x00000000
CPUEAXH_EXCEPTION_DE = 0xE0000000
CPUEAXH_EXCEPTION_GP = 0xE0000001
CPUEAXH_EXCEPTION_SS = 0xE0000002
CPUEAXH_EXCEPTION_NP = 0xE0000003
CPUEAXH_EXCEPTION_UD = 0xE0000004
CPUEAXH_EXCEPTION_PF = 0xE0000005
CPUEAXH_EXCEPTION_AC = 0xE0000006

CPUEAXH_X86_REG_RAX = 0
CPUEAXH_X86_REG_RCX = 1
CPUEAXH_X86_REG_RDX = 2
CPUEAXH_X86_REG_RBX = 3
CPUEAXH_X86_REG_RSP = 4
CPUEAXH_X86_REG_RBP = 5
CPUEAXH_X86_REG_RSI = 6
CPUEAXH_X86_REG_RDI = 7
CPUEAXH_X86_REG_R8 = 8
CPUEAXH_X86_REG_R9 = 9
CPUEAXH_X86_REG_R10 = 10
CPUEAXH_X86_REG_R11 = 11
CPUEAXH_X86_REG_R12 = 12
CPUEAXH_X86_REG_R13 = 13
CPUEAXH_X86_REG_R14 = 14
CPUEAXH_X86_REG_R15 = 15
CPUEAXH_X86_REG_RIP = 16
CPUEAXH_X86_REG_EFLAGS = 17
CPUEAXH_X86_REG_PROCESSOR_ID = 94

__all__ = [name for name in globals() if name.startswith("CPUEAXH_")]
